### ISSUE TITLE
Error message from FIJI GUI

### ISSUE THREAD

**Issue by grigorios-oikonomou** [jefferis/fiji-cmtk-gui#16]
Hi,

I am getting the following error message when trying to run the GUI. Do you have any ideas what might be causing this?

Many thanks,
Grigorios

bindir is /Applications/Fiji.app/bin/cmtk
munger is /Applications/Fiji.app/bin/cmtk/munger
Jefferis, Potter 2007
Chosen reg params: Cachero, Ostrovsky 2010
/Users/grigoriosoikonomou/Documents/Prober_Lab/zBrain/registration/refbrain/Ref20131120pt14pl2.nrrd
refbrain/Ref20131120pt14pl2.nrrd
Cachero, Ostrovsky 2010
"/Applications/Fiji.app/bin/cmtk/munger" -b "/Applications/Fiji.app/bin/cmtk" -a -w -r 010203  -T 8 -X 52 -C 8 -G 80 -R 3 -A ‘--accuracy 0.4’ -W ‘--accuracy 1.6’  -T 4 -s "refbrain/Ref20131120pt14pl2.nrrd" images
[ERROR] null
Traceback (most recent call last):
  File "CMTK_Registration/CMTK_Registration_GUI.py", line 211, in <module>
  File "CMTK_Registration/CMTK_Registration_GUI.py", line 211, in <module>
  File "__pyclasspath__/cmtkgui$py.class", line 95, in makescript
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 229: ordinal not in range(128)

	at org.python.core.codecs.strict_errors(codecs.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.python.core.JavaFunc.__call__(Py.java:2426)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.codecs.encoding_error(codecs.java:1538)
	at org.python.core.codecs.PyUnicode_EncodeIntLimited(codecs.java:1211)
	at org.python.core.codecs.PyUnicode_EncodeASCII(codecs.java:1170)
	at org.python.core.codecs.encode(codecs.java:165)
	at org.python.core.PyString.encode(PyString.java:3896)
	at org.python.core.PyFile.asWritable(PyFile.java:494)
	at org.python.core.PyFile.file_write(PyFile.java:454)
	at org.python.core.PyFile$file_write_exposer.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at cmtkgui$py.makescript$7(/Applications/Fiji.app/plugins/CMTK_Registration/cmtkgui.py:98)
	at cmtkgui$py.call_function(/Applications/Fiji.app/plugins/CMTK_Registration/cmtkgui.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyFunction.function___call__(PyFunction.java:471)
	at org.python.core.PyFunction.__call__(PyFunction.java:466)
	at org.python.pycode._pyx7.f$0(CMTK_Registration/CMTK_Registration_GUI.py:219)
	at org.python.pycode._pyx7.call_function(CMTK_Registration/CMTK_Registration_GUI.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:40)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jefferis** [comment]
Hmm. Is it possible that one of the input folders/files has a non ascii character in the name? u2018 looks like it is a single quote.

**Comment by grigorios-oikonomou** [comment]
Yes! That's why I closed the issue :) I was copy pasting from a publication into a TextEdit and assumed that all the characters would be kosher; I was clearly wrong. Thanks for your help and sorry to have bothered you!
