### ISSUE TITLE
Problems with installing on Windows

### ISSUE THREAD

**Issue by CarolaSt** [jefferis/fiji-cmtk-gui#18]
Hi Gregory,
 
I am having problems installing the Fiji CMTK gui on a Windows computer (I tried Windows 7 and Windows 10). I followed the direction as outlined in the readme file but when I try to run 'Install CMTK' a Java console window opens and I get the following error message (see below). I am rather a novice with image registration and it could be that there is an easy fix. Any suggestions for trouble shooting would be really helpful. 
Thank you very much for your help.

Best,
Carola

> console: Failed to install '': java.nio.charset.UnsupportedCharsetException: cp0.
> [ERROR] null
> Traceback (most recent call last):
>   File "CMTK_Registration/Install_CMTK.py", line 11, in <module>
>   File "C:\FIJI-W~1\Fiji.app\plugins\CMTK_Registration\cmtkgui.py", line 5, in <module>
>     import subprocess, re, urllib2, tempfile
>   File "C:\FIJI-W~1\Fiji.app\jars\jython-shaded-2.7.1.jar\Lib\subprocess.py", line 799, in <module>
>   File "C:\FIJI-W~1\Fiji.app\jars\jython-shaded-2.7.1.jar\Lib\subprocess.py", line 1399, in Popen
>   File "C:\FIJI-W~1\Fiji.app\jars\jython-shaded-2.7.1.jar\Lib\ctypes\__init__.py", line 281, in __getattr__
>   File "C:\FIJI-W~1\Fiji.app\jars\jython-shaded-2.7.1.jar\Lib\ctypes\__init__.py", line 262, in __init__
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign.newLoadError(Foreign.java:72)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign.access$300(Foreign.java:42)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign$InValidInstanceHolder.getForeign(Foreign.java:98)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Library.openLibrary(Library.java:157)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Library.getCachedInstance(Library.java:131)
> 	at org.python.modules.jffi.DynamicLibrary.<init>(DynamicLibrary.java:26)
> 	at org.python.modules.jffi.jffi.dlopen(jffi.java:43)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: org.scijava.jython.shaded.com.kenai.jffi.Foreign.getVersion()I
> 
> 	at org.python.core.Py.JavaError(Py.java:552)
> 	at org.python.core.Py.JavaError(Py.java:543)
> 	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
> 	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206)
> 	at org.python.core.PyObject.__call__(PyObject.java:497)
> 	at org.python.core.PyObject.__call__(PyObject.java:501)
> 	at ctypes$py.__init__$49(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/ctypes/__init__.py:262)
> 	at ctypes$py.call_function(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/ctypes/__init__.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:171)
> 	at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
> 	at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
> 	at org.python.core.PyFunction.__call__(PyFunction.java:482)
> 	at org.python.core.PyFunction.__call__(PyFunction.java:476)
> 	at org.python.core.PyInstance.__init__(PyInstance.java:124)
> 	at org.python.core.PyClass.__call__(PyClass.java:193)
> 	at org.python.core.PyObject.__call__(PyObject.java:480)
> 	at org.python.core.PyObject.__call__(PyObject.java:484)
> 	at ctypes$py.__getattr__$54(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/ctypes/__init__.py:283)
> 	at ctypes$py.call_function(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/ctypes/__init__.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:171)
> 	at org.python.core.PyBaseCode.call(PyBaseCode.java:154)
> 	at org.python.core.PyFunction.__call__(PyFunction.java:423)
> 	at org.python.core.PyMethod.__call__(PyMethod.java:141)
> 	at org.python.core.PyMethod.__call__(PyMethod.java:132)
> 	at org.python.core.Deriveds.__findattr_ex__(Deriveds.java:81)
> 	at org.python.core.PyObjectDerived.__findattr_ex__(PyObjectDerived.java:1036)
> 	at org.python.core.PyObject.__getattr__(PyObject.java:1025)
> 	at subprocess$py.Popen$22(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/subprocess.py:1886)
> 	at subprocess$py.call_function(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/subprocess.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:171)
> 	at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
> 	at org.python.core.Py.makeClass(Py.java:2066)
> 	at org.python.core.Py.makeClass(Py.java:2060)
> 	at subprocess$py.f$0(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/subprocess.py:2013)
> 	at subprocess$py.call_function(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/subprocess.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:171)
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.imp.createFromCode(imp.java:436)
> 	at org.python.core.util.importer.importer_load_module(importer.java:116)
> 	at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:170)
> 	at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
> 	at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:46)
> 	at org.python.core.imp.loadFromLoader(imp.java:593)
> 	at org.python.core.imp.find_module(imp.java:547)
> 	at org.python.core.imp.import_next(imp.java:838)
> 	at org.python.core.imp.import_module_level(imp.java:957)
> 	at org.python.core.imp.importName(imp.java:1057)
> 	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
> 	at org.python.core.PyObject.__call__(PyObject.java:450)
> 	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
> 	at org.python.core.imp.importOne(imp.java:1076)
> 	at cmtkgui$py.f$0(C:/FIJI-W~1/Fiji.app/plugins/CMTK_Registration/cmtkgui.py:372)
> 	at cmtkgui$py.call_function(C:/FIJI-W~1/Fiji.app/plugins/CMTK_Registration/cmtkgui.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:171)
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.imp.createFromCode(imp.java:436)
> 	at org.python.core.imp.createFromPyClass(imp.java:237)
> 	at org.python.core.imp.createFromPyClass(imp.java:205)
> 	at org.python.core.imp.loadFromSource(imp.java:657)
> 	at org.python.core.imp.find_module(imp.java:551)
> 	at org.python.core.imp.import_next(imp.java:838)
> 	at org.python.core.imp.import_module_level(imp.java:957)
> 	at org.python.core.imp.importName(imp.java:1057)
> 	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
> 	at org.python.core.PyObject.__call__(PyObject.java:450)
> 	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
> 	at org.python.core.imp.importOne(imp.java:1076)
> 	at org.python.pycode._pyx0.f$0(CMTK_Registration/Install_CMTK.py:81)
> 	at org.python.pycode._pyx0.call_function(CMTK_Registration/Install_CMTK.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:171)
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.Py.runCode(Py.java:1614)
> 	at org.python.core.__builtin__.eval(__builtin__.java:497)
> 	at org.python.core.__builtin__.eval(__builtin__.java:501)
> 	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
> 	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
> 	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
> 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
> 	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
> 	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
> 	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.UnsatisfiedLinkError: org.scijava.jython.shaded.com.kenai.jffi.Foreign.getVersion()I
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign.newLoadError(Foreign.java:72)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign.access$300(Foreign.java:42)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign$InValidInstanceHolder.getForeign(Foreign.java:98)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Library.openLibrary(Library.java:157)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Library.getCachedInstance(Library.java:131)
> 	at org.python.modules.jffi.DynamicLibrary.<init>(DynamicLibrary.java:26)
> 	at org.python.modules.jffi.jffi.dlopen(jffi.java:43)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
> 	... 84 more
> Caused by: java.lang.UnsatisfiedLinkError: org.scijava.jython.shaded.com.kenai.jffi.Foreign.getVersion()I
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign.getVersion(Native Method)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:53)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Type.resolveSize(Type.java:155)
> 	at org.scijava.jython.shaded.com.kenai.jffi.Type.size(Type.java:138)
> 	at org.scijava.jython.shaded.jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:187)
> 	at org.scijava.jython.shaded.jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
> 	at org.scijava.jython.shaded.jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:66)
> 	at org.scijava.jython.shaded.jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
> 	at org.scijava.jython.shaded.jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:62)
> 	at org.scijava.jython.shaded.jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:58)
> 	at org.scijava.jython.shaded.jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
> 	at java.lang.Class.newInstance(Class.java:442)
> 	at org.scijava.jython.shaded.jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
> 	at org.scijava.jython.shaded.jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
> 	at org.scijava.jython.shaded.jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
> 	at org.scijava.jython.shaded.jnr.ffi.Library.loadLibrary(Library.java:114)
> 	at org.scijava.jython.shaded.jnr.posix.POSIXFactory$DefaultLibCProvider$SingletonHolder.<clinit>(POSIXFactory.java:279)
> 	at org.scijava.jython.shaded.jnr.posix.POSIXFactory$DefaultLibCProvider.getLibC(POSIXFactory.java:283)
> 	at org.scijava.jython.shaded.jnr.posix.BaseNativePOSIX.<init>(BaseNativePOSIX.java:37)
> 	at org.scijava.jython.shaded.jnr.posix.WindowsPOSIX.<init>(WindowsPOSIX.java:132)
> 	at org.scijava.jython.shaded.jnr.posix.POSIXFactory.loadWindowsPOSIX(POSIXFactory.java:163)
> 	at org.scijava.jython.shaded.jnr.posix.POSIXFactory.loadNativePOSIX(POSIXFactory.java:136)
> 	at org.scijava.jython.shaded.jnr.posix.POSIXFactory.loadPOSIX(POSIXFactory.java:90)
> 	at org.scijava.jython.shaded.jnr.posix.LazyPOSIX.loadPOSIX(LazyPOSIX.java:38)
> 	at org.scijava.jython.shaded.jnr.posix.LazyPOSIX.posix(LazyPOSIX.java:32)
> 	at org.scijava.jython.shaded.jnr.posix.LazyPOSIX.isNative(LazyPOSIX.java:382)
> 	at org.python.modules.posix.PosixModule.classDictInit(PosixModule.java:131)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.python.core.PyJavaType.init(PyJavaType.java:571)
> 	at org.python.core.PyType.createType(PyType.java:1523)
> 	at org.python.core.PyType.addFromClass(PyType.java:1462)
> 	at org.python.core.PyType.fromClass(PyType.java:1551)
> 	at org.python.core.imp.createFromClass(imp.java:469)
> 	at org.python.core.imp.loadBuiltin(imp.java:578)
> 	at org.python.core.imp.find_module(imp.java:534)
> 	at org.python.core.imp.import_next(imp.java:838)
> 	at org.python.core.imp.import_module_level(imp.java:957)
> 	at org.python.core.imp.importName(imp.java:1057)
> 	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
> 	at org.python.core.PyObject.__call__(PyObject.java:450)
> 	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
> 	at org.python.core.imp.importAll(imp.java:1176)
> 	at os$py.f$0(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/os.py:726)
> 	at os$py.call_function(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/os.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:171)
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.imp.createFromCode(imp.java:436)
> 	at org.python.core.util.importer.importer_load_module(importer.java:116)
> 	at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:170)
> 	at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
> 	at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:46)
> 	at org.python.core.imp.loadFromLoader(imp.java:593)
> 	at org.python.core.imp.find_module(imp.java:547)
> 	at org.python.core.imp.import_next(imp.java:838)
> 	at org.python.core.imp.import_module_level(imp.java:957)
> 	at org.python.core.imp.importName(imp.java:1057)
> 	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
> 	at org.python.core.PyObject.__call__(PyObject.java:450)
> 	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
> 	at org.python.core.imp.importOne(imp.java:1076)
> 	at site$py.f$0(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/site.py:637)
> 	at site$py.call_function(C:/FIJI-W~1/Fiji.app/jars/jython-shaded-2.7.1.jar/Lib/site.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:171)
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.imp.createFromCode(imp.java:436)
> 	at org.python.core.util.importer.importer_load_module(importer.java:116)
> 	at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:170)
> 	at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
> 	at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:46)
> 	at org.python.core.imp.loadFromLoader(imp.java:593)
> 	at org.python.core.imp.find_module(imp.java:547)
> 	at org.python.core.imp.import_next(imp.java:838)
> 	at org.python.core.imp.import_first(imp.java:863)
> 	at org.python.core.imp.load(imp.java:721)
> 	at org.python.core.Py.importSiteIfSelected(Py.java:1795)
> 	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:116)
> 	at org.python.util.PythonInterpreter.threadLocalStateInterpreter(PythonInterpreter.java:81)
> 	at org.python.jsr223.PyScriptEngine.<init>(PyScriptEngine.java:27)
> 	at org.python.jsr223.PyScriptEngineFactory.getScriptEngine(PyScriptEngineFactory.java:85)
> 	at org.scijava.script.AdaptedScriptLanguage.getScriptEngine(AdaptedScriptLanguage.java:140)
> 	at org.scijava.script.ScriptModule.getEngine(ScriptModule.java:108)
> 	at org.scijava.script.ScriptModule.run(ScriptModule.java:129)
> 	... 8 more

**Comment by MaximilianHoffmann** [comment]
I experience the same error on windows

**Comment by uherget** [comment]
Same here.
I solved the first error (java.nio.charset.UnsupportedCharsetException: cp0) by launching Fiji with the parameter "-Dpython.console.encoding=UTF-8", but I can't find any solution for the other one (java.lang.UnsatisfiedLinkError: org.scijava.jython.shaded.com.kenai.jffi.Foreign.getVersion()I).
